#!/usr/bin/env python3
"""Generate a cross-run prompt-serialization association table from verified JSON."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MODEL_LABELS = {
    "Qwen/Qwen3-4B": "Qwen3-4B",
    "Qwen/Qwen3-8B": "Qwen3-8B",
    "Qwen/Qwen3-14B": "Qwen3-14B",
    "mistralai/Mistral-7B-Instruct-v0.3": "Mistral-7B",
    "allenai/OLMo-2-1124-7B-Instruct": "OLMo-2-7B",
    "microsoft/Phi-4-mini-instruct": "Phi-4-mini",
}
ORDER = tuple(MODEL_LABELS)
METRICS = ("parse", "executable", "goal_valid", "partial_order", "exact")


def effect_cell(effect: dict) -> str:
    marker = r"$^{\dagger}$" if effect["holm_reject_0_05"] else ""
    return (
        f"{100 * effect['estimate']:+.1f} "
        f"[{100 * effect['ci95_low']:+.1f}, {100 * effect['ci95_high']:+.1f}]{marker}"
    )


def render(report: dict) -> str:
    if report.get("evidence_status") != "controlled_same_seed_same_domain_prompt_serialization_comparison":
        raise ValueError("unexpected prompt-effect evidence status")
    if report.get("bootstrap", {}).get("trials") != 10_000:
        raise ValueError("prompt-effect report must use 10,000 paired trials")
    rows = {row["model_id"]: row for row in report.get("models", [])}
    if set(rows) != set(ORDER):
        raise ValueError("prompt-effect report must contain the frozen six-model set")
    significant_counts = {
        metric: sum(rows[model]["effects"][metric]["holm_reject_0_05"] for model in ORDER)
        for metric in METRICS
    }
    largest_goal = max(ORDER, key=lambda model: abs(rows[model]["effects"]["goal_valid"]["estimate"]))
    largest_goal_effect = rows[largest_goal]["effects"]["goal_valid"]["estimate"]
    largest_goal_direction = "increase" if largest_goal_effect >= 0 else "decrease"

    lines = [
        "% Generated by paper/scripts/generate_prompt_effect_data.py; do not edit.",
        rf"\newcommand{{\PromptEffectSignificantGoalCount}}{{{significant_counts['goal_valid']}}}",
        rf"\newcommand{{\PromptEffectSignificantExactCount}}{{{significant_counts['exact']}}}",
        rf"\newcommand{{\PromptEffectLargestGoalModel}}{{{MODEL_LABELS[largest_goal]}}}",
        rf"\newcommand{{\PromptEffectLargestGoalMagnitude}}{{{abs(100 * largest_goal_effect):.1f}}}",
        rf"\newcommand{{\PromptEffectLargestGoalDirection}}{{{largest_goal_direction}}}",
        r"\newcommand{\PromptSerializationEffectTable}{%",
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Cross-run sensitivity between the archived v0.4 serialization and the uniform compact serialization. Entries are v0.6-minus-v0.4 percentage points with paired task-bootstrap 95\% intervals. $\dagger$ denotes a Holm-adjusted paired sign-flip summary across the six models for that metric. The archived run used A40 GPUs and the v0.6 run used an RTX 4080 SUPER.}",
        r"\label{tab:prompt-serialization-effect}",
        r"\scriptsize",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{lrrrrr}",
        r"\toprule",
        r"Model & Parse & Executable & Goal valid & Partial order & Exact \\",
        r"\midrule",
    ]
    for model in ORDER:
        effects = rows[model]["effects"]
        cells = " & ".join(effect_cell(effects[metric]) for metric in METRICS)
        lines.append(f"{MODEL_LABELS[model]} & {cells} \\\\")
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}%",
            r"}",
            r"\end{table*}%",
            r"}",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        type=Path,
        default=ROOT / "artifacts" / "prompt_serialization_effect_v0_6.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "paper" / "generated_prompt_effect.tex",
    )
    args = parser.parse_args()
    report = json.loads(args.input.read_text(encoding="utf-8"))
    args.output.write_text(render(report), encoding="utf-8")
    print(args.output)


if __name__ == "__main__":
    main()
