#!/usr/bin/env python3
"""Generate fail-closed LaTeX macros from completed human review artifacts."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from scripts.verify_v02_release import verify_human_review


ROOT = Path(__file__).resolve().parents[2]
REQUIRED = (
    "semantic_review_reviewer_a_v0_3.json",
    "semantic_review_reviewer_b_v0_3.json",
    "semantic_review_agreement_v0_3.json",
    "novel_valid_reviewed_v0_1.json",
)
FIELD_LABELS = (
    ("source_to_compiled_goal", "Goal compilation"),
    ("action_preconditions", "Action preconditions"),
    ("action_effects", "Action effects"),
    ("trace_plausibility_at_declared_abstraction", "Trace plausibility"),
    ("selective_closed_world_assumptions", "Closed-world assumptions"),
    ("decision", "Overall decision"),
)
CLASSIFICATION_MACROS = {
    "valid_novel_or_nonminimal_plan": "HumanNovelValidCount",
    "constructed_family_coverage_miss": "HumanNovelCoverageMissCount",
    "action_semantics_or_evaluator_issue": "HumanNovelEvaluatorIssueCount",
    "not_semantically_valid": "HumanNovelInvalidCount",
}


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def macro(name: str, value: object) -> str:
    return rf"\newcommand{{\{name}}}{{{value}}}"


def build_macros(result_dir: Path) -> str:
    present = [(result_dir / name).is_file() for name in REQUIRED]
    if any(present) and not all(present):
        missing = [name for name, exists in zip(REQUIRED, present) if not exists]
        raise FileNotFoundError(
            "partial human-review evidence; missing " + ", ".join(missing)
        )

    lines = ["% Generated by paper/scripts/generate_human_review_data.py"]
    if not any(present):
        lines.extend(
            [
                macro("HumanReviewEvidenceReady", 0),
                macro("HumanReviewTaskCount", 0),
                macro("HumanReviewDisagreementCount", 0),
                macro("HumanReviewAgreementRows", ""),
            ]
        )
        for name in CLASSIFICATION_MACROS.values():
            lines.append(macro(name, 0))
        return "\n".join(lines) + "\n"

    verify_human_review(result_dir)
    agreement = load(result_dir / "semantic_review_agreement_v0_3.json")
    reviewed = load(result_dir / "novel_valid_reviewed_v0_1.json")
    rows = []
    for field, label in FIELD_LABELS:
        values = agreement["per_field"][field]
        agreement_percent = 100.0 * values["agreement_rate"]
        kappa = values["cohen_kappa"]
        kappa_text = "--" if kappa is None else f"{kappa:.3f}"
        rows.append(f"{label} & {agreement_percent:.1f} & {kappa_text} \\\\")

    counts = {key: 0 for key in CLASSIFICATION_MACROS}
    for case in reviewed["cases"]:
        counts[case["review"]["classification"]] += 1

    lines.extend(
        [
            macro("HumanReviewEvidenceReady", 1),
            macro("HumanReviewTaskCount", agreement["task_count"]),
            macro("HumanReviewDisagreementCount", agreement["disagreement_count"]),
            macro("HumanReviewAgreementRows", "\n".join(rows)),
        ]
    )
    for classification, name in CLASSIFICATION_MACROS.items():
        lines.append(macro(name, counts[classification]))
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--result-dir", type=Path, default=ROOT / "artifacts")
    parser.add_argument(
        "--output", type=Path, default=ROOT / "paper" / "generated_human_review.tex"
    )
    args = parser.parse_args()
    args.output.write_text(build_macros(args.result_dir), encoding="utf-8")
    print(args.output)


if __name__ == "__main__":
    main()
