#!/usr/bin/env python3
"""Generate LaTeX macros for the full frozen v0.5 Codex audit."""
from __future__ import annotations

from collections import Counter
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ARTIFACTS = ROOT / "artifacts"
PAPER = ROOT / "paper"


def load(name: str) -> dict:
    return json.loads((ARTIFACTS / name).read_text(encoding="utf-8"))


def main() -> None:
    left = load("semantic_review_codex_astra_formal_v0_5.json")
    right = load("semantic_review_codex_sol_adversarial_v0_5.json")
    agreement = load("semantic_review_codex_ai_agreement_v0_5.json")
    decision = agreement["per_field"]["decision"]
    if agreement["task_count"] != 100:
        raise ValueError("v0.5 semantic audit must contain 100 tasks")
    if agreement["packet_version"] != "planspace-semantic-review-v0.4":
        raise ValueError("unexpected frozen packet version")
    left_counts = Counter(task["review"]["decision"] for task in left["tasks"])
    right_counts = Counter(task["review"]["decision"] for task in right["tasks"])
    lines = [
        "% Generated by paper/scripts/generate_semantic_v05_data.py; do not edit.",
        rf"\newcommand{{\SemanticVFiveTaskCount}}{{{agreement['task_count']}}}",
        rf"\newcommand{{\SemanticVFiveDecisionAgreementCount}}{{{decision['agreement_count']}}}",
        rf"\newcommand{{\SemanticVFiveDecisionAgreementRate}}{{{100 * decision['agreement_rate']:.1f}}}",
        rf"\newcommand{{\SemanticVFiveDecisionDisagreementCount}}{{{decision['task_count'] - decision['agreement_count']}}}",
        rf"\newcommand{{\SemanticVFiveReviewerAApprove}}{{{left_counts['approve']}}}",
        rf"\newcommand{{\SemanticVFiveReviewerARevise}}{{{left_counts['revise']}}}",
        rf"\newcommand{{\SemanticVFiveReviewerBApprove}}{{{right_counts['approve']}}}",
        rf"\newcommand{{\SemanticVFiveReviewerBRevise}}{{{right_counts['revise']}}}",
    ]
    output = PAPER / "generated_semantic_v05.tex"
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(output)


if __name__ == "__main__":
    main()
