#!/usr/bin/env python3
"""Compile checked-in JSON diagnostics into LaTeX macros.

This keeps the development table and bar chart synchronized with the artifacts.
"""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"

TASKS = [
    ("installing_a_printer", "Printer", "Installing printer", "bounded paths"),
    ("opening_doors", "Doors", "Opening doors", "bounded paths"),
    ("moving_boxes_to_storage", "Boxes", "Moving boxes", "bounded paths"),
    ("organizing_file_cabinet", "Files", "Organizing files", "bounded paths"),
    ("storing_food", "Food", "Storing food", "bounded states"),
]


def length_text(values):
    lo, hi = min(values), max(values)
    return str(lo) if lo == hi else "%d--%d" % (lo, hi)


lines = ["% Generated by scripts/generate_paper_data.py; do not edit by hand."]
for activity, macro, display, completeness in TASKS:
    path = DATA / (activity + "_v3_9_2_candidate_metrics.json")
    with path.open("r", encoding="utf-8") as handle:
        record = json.load(handle)
    if record["evidence_status"] != "frozen_bddl_candidate_semantics_not_paper_evidence":
        raise ValueError("Unexpected evidence status for " + activity)
    frr = 100.0 * record["single_reference_false_rejection_rate"]
    lines.append("\\newcommand{\\%sFRR}{%.2f}" % (macro, frr))
    row = "%s & %d & %s & %d & %.2f & %s \\\\" % (
        display,
        record["plan_count"],
        length_text(record["plan_lengths"]),
        record["structured_negative_count"],
        frr,
        completeness,
    )
    lines.append("\\newcommand{\\%sRow}{%s}" % (macro, row))

(ROOT / "generated_results.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
