#!/usr/bin/env python3
"""Generate LaTeX macros and rows from frozen confirmatory artifacts."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional


ROOT = Path(__file__).resolve().parents[2]
PAPER = ROOT / "paper"
ARTIFACTS = ROOT / "artifacts"

MODEL_SPECS = [
    (
        "Qwen/Qwen3-8B",
        "Qwen3-8B",
        ARTIFACTS / "qwen3_8b_queue_100_analysis_v0_1.json",
    ),
    (
        "Qwen/Qwen3-4B",
        "Qwen3-4B",
        ARTIFACTS / "qwen3_4b_queue_100_analysis_v0_1.json",
    ),
    (
        "microsoft/Phi-4-mini-instruct",
        "Phi-4-mini",
        ARTIFACTS / "phi4_mini_queue_100_analysis_v0_1.json",
    ),
]

SPLIT_LABELS = [
    ("iid_core", "Core"),
    ("ood_commutation", "Commutation"),
    ("ood_goal_choice", "Goal choice"),
    ("ood_long_horizon", "Long horizon"),
    ("ood_operator_composition", "Operator composition"),
]


def pct(value: Optional[float]) -> str:
    return "--" if value is None else f"{100 * value:.1f}"


def interval(item: dict[str, float]) -> str:
    return f"{pct(item['estimate'])} [{pct(item['ci95_low'])}, {pct(item['ci95_high'])}]"


def main() -> None:
    audit = json.loads(
        (ARTIFACTS / "generic_domain_audit_100_v0_4.json").read_text(encoding="utf-8")
    )
    analyses = {}
    for model_id, display, path in MODEL_SPECS:
        report = json.loads(path.read_text(encoding="utf-8"))
        if report["model_id"] != model_id:
            raise ValueError(f"model mismatch in {path}")
        analyses[model_id] = (display, report)
    comparison = json.loads(
        (ARTIFACTS / "three_model_comparison_v0_1.json").read_text(encoding="utf-8")
    )
    controls = json.loads(
        (ARTIFACTS / "deterministic_controls_100_v0_4.json").read_text(encoding="utf-8")
    )
    truncation = json.loads(
        (ARTIFACTS / "truncation_retry_analysis_v0_1.json").read_text(encoding="utf-8")
    )
    sampling = json.loads(
        (ARTIFACTS / "sampling_curve_analysis_v0_1.json").read_text(encoding="utf-8")
    )
    bounded_coverage = json.loads(
        (ARTIFACTS / "bounded_family_coverage_v0_4.json").read_text(encoding="utf-8")
    )
    sensitivity = {}
    for model_id, display, path in MODEL_SPECS:
        suffix = "_queue_100_analysis_v0_1.json"
        if not path.name.endswith(suffix):
            raise ValueError(f"unexpected analysis artifact name: {path.name}")
        slug = path.name[: -len(suffix)]
        report = json.loads(
            (ARTIFACTS / f"{slug}_action_prefix_sensitivity_v0_1_posthoc.json").read_text(
                encoding="utf-8"
            )
        )
        if report["model_id"] != model_id:
            raise ValueError(f"sensitivity model mismatch for {slug}")
        sensitivity[model_id] = (display, report)

    summary = audit["summary"]
    lines = [
        "% Generated by paper/scripts/generate_confirmatory_data.py; do not edit.",
        r"\newcommand{\ConfirmatoryTaskCount}{%d}" % summary["queue_task_count"],
        r"\newcommand{\GoalPlanRepresentativeCount}{%d}"
        % summary["unique_goal_plan_representative_count"],
        r"\newcommand{\MultiplicityTaskCount}{%d}"
        % summary["tasks_with_any_observed_multiplicity"],
        r"\newcommand{\TopoCheckedCount}{%s}"
        % f"{summary['topological_orders_checked']:,}",
        r"\newcommand{\TopoValidCount}{%s}"
        % f"{summary['topological_orders_valid']:,}",
        r"\newcommand{\ControlPositiveExact}{%s}"
        % pct(controls["summary"]["positive_exact_match_rate"]),
        r"\newcommand{\ControlPositiveGoal}{%s}"
        % pct(controls["summary"]["positive_goal_valid_rate"]),
        r"\newcommand{\ControlDeletionReject}{%s}"
        % pct(controls["summary"]["deletion_negative_rejection_rate"]),
        r"\newcommand{\VFourBoundedCoverageTaskCount}{%d}"
        % bounded_coverage["summary"]["exhaustively_analyzed_task_count"],
        r"\newcommand{\VFourBoundedValidPlanCount}{%s}"
        % f"{bounded_coverage['summary']['bounded_valid_plan_count']:,}",
        r"\newcommand{\VFourBoundedCoveredPlanCount}{%s}"
        % f"{bounded_coverage['summary']['bounded_valid_plan_covered_count']:,}",
        r"\newcommand{\VFourBoundedCoverageRate}{%.2f}"
        % (100 * bounded_coverage["summary"]["micro_bounded_family_coverage"]),
        r"\newcommand{\VFourBoundedFullCoverageTaskCount}{%d}"
        % bounded_coverage["summary"]["tasks_with_full_bounded_coverage"],
    ]

    model_rows = []
    for model_id, display, _ in MODEL_SPECS:
        aggregate = comparison["aggregate"][model_id]
        model_rows.append(
            f"{display} & {pct(aggregate['parse'])} & {pct(aggregate['executable'])} & "
            f"{pct(aggregate['goal_valid'])} & {pct(aggregate['partial_order'])} & "
            f"{pct(aggregate['exact'])} & {pct(aggregate['false_rejection_among_valid'])} \\\\"
        )
    lines.append("\\newcommand{\\ConfirmatoryModelRows}{%")
    lines.extend(row + "%" for row in model_rows)
    lines.append("}")

    sensitivity_rows = []
    for model_id, display, _ in MODEL_SPECS:
        item = sensitivity[model_id][1]["summary"]
        sensitivity_rows.append(
            f"{display} & {pct(item['strict_parse_rate'])} & "
            f"{pct(item['normalized_parse_rate'])} & "
            f"{pct(item['strict_goal_valid_rate'])} & "
            f"{pct(item['normalized_goal_valid_rate'])} & "
            f"{pct(item['strict_exact_match_rate'])} & "
            f"{pct(item['normalized_exact_match_rate'])} \\\\"
        )
    lines.append("\\newcommand{\\InterfaceSensitivityRows}{%")
    lines.extend(row + "%" for row in sensitivity_rows)
    lines.append("}")

    sampling_by_model = {row["model_id"]: row for row in sampling["models"]}
    diversity_rows = []
    for model_id, display, _ in MODEL_SPECS:
        aggregate = comparison["aggregate"][model_id]
        points = {
            point["k"]: point["metrics"]
            for point in sampling_by_model[model_id]["points"]
        }
        diversity_rows.append(
            f"{display} & {pct(points[1]['any_goal_valid_rate']['estimate'])} & "
            f"{pct(points[5]['any_goal_valid_rate']['estimate'])} & "
            f"{pct(points[1]['mean_reference_family_coverage']['estimate'])} & "
            f"{pct(points[5]['mean_reference_family_coverage']['estimate'])} & "
            f"{points[5]['mean_unique_valid_plans']['estimate']:.2f} & "
            f"{100 * aggregate['mean_normalized_cost_regret_among_valid']:.1f} \\\\"
        )
    lines.append("\\newcommand{\\DiversityCostRows}{%")
    lines.extend(row + "%" for row in diversity_rows)
    lines.append("}")

    split_rows = []
    first_analysis = next(iter(analyses.values()))[1]
    split_counts = {
        key: first_analysis["strata"]["structural_split"][key]["task_count"]
        for key, _ in SPLIT_LABELS
    }
    for split, label in SPLIT_LABELS:
        values = [
            pct(analyses[model_id][1]["strata"]["structural_split"][split]["goal_valid_rate"])
            for model_id, _, _ in MODEL_SPECS
        ]
        split_rows.append(
            f"{label} & {split_counts[split]} & " + " & ".join(values) + r" \\"
        )
    lines.append("\\newcommand{\\StructuralSplitRows}{%")
    lines.extend(row + "%" for row in split_rows)
    lines.append("}")

    display_by_id = {model_id: display for model_id, display, _ in MODEL_SPECS}
    truncation_rows = []
    for row in truncation["models"]:
        display = display_by_id[row["model_id"]]
        truncation_rows.append(
            f"{display} & {row['task_count']} & {pct(row['base']['parse'])} & "
            f"{pct(row['base']['goal'])} & {pct(row['retry']['parse'])} & "
            f"{pct(row['retry']['goal'])} \\\\"
        )
    lines.append("\\newcommand{\\TruncationRows}{%")
    lines.extend(row + "%" for row in truncation_rows)
    lines.append("}")

    paired_rows = []
    qwen_pair = None
    for comparison_item in comparison["paired_comparisons"]:
        left = display_by_id[comparison_item["left_model"]]
        right = display_by_id[comparison_item["right_model"]]
        exact = comparison_item["metric_differences"]["exact"]
        goal = comparison_item["metric_differences"]["goal_valid"]
        paired_rows.append(
            f"{left} $-$ {right} & {interval(exact)} & {interval(goal)} \\\\"
        )
        if (
            comparison_item["left_model"] == "Qwen/Qwen3-8B"
            and comparison_item["right_model"] == "Qwen/Qwen3-4B"
        ):
            qwen_pair = (exact, goal)
    lines.append("\\newcommand{\\PairedDifferenceRows}{%")
    lines.extend(row + "%" for row in paired_rows)
    lines.append("}")
    if qwen_pair is None:
        raise ValueError("missing Qwen3-8B versus Qwen3-4B comparison")
    exact, goal = qwen_pair
    lines.extend(
        [
            r"\newcommand{\QwenPairExactDifference}{%s pp [95\%% CI %s, %s]}"
            % (pct(exact["estimate"]), pct(exact["ci95_low"]), pct(exact["ci95_high"])),
            r"\newcommand{\QwenPairGoalDifference}{%s pp [95\%% CI %s, %s]}"
            % (pct(goal["estimate"]), pct(goal["ci95_low"]), pct(goal["ci95_high"])),
        ]
    )

    primary = analyses["Qwen/Qwen3-8B"][1]["bootstrap"]["metrics"]
    phi_analysis = analyses["microsoft/Phi-4-mini-instruct"][1]
    phi_sensitivity = sensitivity["microsoft/Phi-4-mini-instruct"][1]
    phi_sensitivity_summary = phi_sensitivity["summary"]
    phi_goal_delta = phi_sensitivity["bootstrap"]["deltas"]["goal_valid_rate_delta"]
    phi_unknown_action_count = phi_analysis["parse_error_types"]["unknown_action_id"]
    lines.extend(
        [
            r"\newcommand{\PrimaryGoalPoint}{%s\%%}"
            % pct(primary["goal_valid_rate"]["estimate"]),
            r"\newcommand{\PrimaryExactPoint}{%s\%%}"
            % pct(primary["exact_match_rate"]["estimate"]),
            r"\newcommand{\PrimaryFRRPoint}{%s\%%}"
            % pct(primary["single_reference_false_rejection_among_valid"]["estimate"]),
            r"\newcommand{\PrimaryGoalCI}{%s\%% [%s\%%, %s\%%]}"
            % (
                pct(primary["goal_valid_rate"]["estimate"]),
                pct(primary["goal_valid_rate"]["ci95_low"]),
                pct(primary["goal_valid_rate"]["ci95_high"]),
            ),
            r"\newcommand{\PrimaryExactCI}{%s\%% [%s\%%, %s\%%]}"
            % (
                pct(primary["exact_match_rate"]["estimate"]),
                pct(primary["exact_match_rate"]["ci95_low"]),
                pct(primary["exact_match_rate"]["ci95_high"]),
            ),
            r"\newcommand{\PrimaryFRRCI}{%s\%% [%s\%%, %s\%%]}"
            % (
                pct(primary["single_reference_false_rejection_among_valid"]["estimate"]),
                pct(primary["single_reference_false_rejection_among_valid"]["ci95_low"]),
                pct(primary["single_reference_false_rejection_among_valid"]["ci95_high"]),
            ),
            r"\newcommand{\PrimaryLengthCapCount}{%d}"
            % analyses["Qwen/Qwen3-8B"][1]["failure_counts"]["length_cap"],
            r"\newcommand{\PhiUnknownActionCount}{%d}" % phi_unknown_action_count,
            r"\newcommand{\PhiUnknownActionRate}{%s}"
            % pct(phi_unknown_action_count / 500),
            r"\newcommand{\PhiNormalizedGoal}{%s\%%}"
            % pct(phi_sensitivity_summary["normalized_goal_valid_rate"]),
            r"\newcommand{\PhiNormalizedExact}{%s\%%}"
            % pct(phi_sensitivity_summary["normalized_exact_match_rate"]),
            r"\newcommand{\PhiGoalNormalizationDeltaCI}{%s pp [95\%% CI %s, %s]}"
            % (
                pct(phi_goal_delta["estimate"]),
                pct(phi_goal_delta["ci95_low"]),
                pct(phi_goal_delta["ci95_high"]),
            ),
        ]
    )

    (PAPER / "generated_confirmatory.tex").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )
    print(PAPER / "generated_confirmatory.tex")


if __name__ == "__main__":
    main()
