#!/usr/bin/env python3
"""Generate LaTeX macros for the frozen v0.4 AI semantic re-audit."""

from __future__ import annotations

from collections import Counter
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
ARTIFACTS = ROOT / "artifacts"
PAPER = ROOT / "paper"


def load(name: str) -> dict:
    return json.loads((ARTIFACTS / name).read_text(encoding="utf-8"))


def main() -> None:
    left = load("semantic_review_codex_astra_a_v0_4.json")
    right = load("semantic_review_codex_sol_b_v0_4.json")
    agreement = load("semantic_review_codex_ai_agreement_v0_4.json")
    adjudication = load("semantic_review_v0_4_adjudication.json")

    if agreement["packet_version"] != "planspace-semantic-review-v0.4":
        raise ValueError("unexpected semantic packet version")
    if agreement["task_count"] != 30:
        raise ValueError("semantic audit must contain 30 tasks")
    decision = agreement["per_field"]["decision"]
    if decision["agreement_count"] < 27:
        raise ValueError("v0.4 decision agreement is below the frozen threshold")
    decisions = [
        task["review"]["decision"]
        for packet in (left, right)
        for task in packet["tasks"]
    ]
    counts = Counter(decisions)
    if counts["reject"] or not adjudication["gate"]["passed"]:
        raise ValueError("v0.4 semantic gate did not pass")

    left_counts = Counter(task["review"]["decision"] for task in left["tasks"])
    right_counts = Counter(task["review"]["decision"] for task in right["tasks"])
    lines = [
        "% Generated by paper/scripts/generate_semantic_v04_data.py; do not edit.",
        rf"\newcommand{{\SemanticVFourTaskCount}}{{{agreement['task_count']}}}",
        rf"\newcommand{{\SemanticVFourDecisionAgreementCount}}{{{decision['agreement_count']}}}",
        rf"\newcommand{{\SemanticVFourDecisionAgreementRate}}{{{100 * decision['agreement_rate']:.1f}}}",
        rf"\newcommand{{\SemanticVFourReviewerAApprove}}{{{left_counts['approve']}}}",
        rf"\newcommand{{\SemanticVFourReviewerARevise}}{{{left_counts['revise']}}}",
        rf"\newcommand{{\SemanticVFourReviewerBApprove}}{{{right_counts['approve']}}}",
        rf"\newcommand{{\SemanticVFourReviewerBRevise}}{{{right_counts['revise']}}}",
        rf"\newcommand{{\SemanticVFourRejectCount}}{{{counts['reject']}}}",
        rf"\newcommand{{\SemanticVFourAdjudicationCount}}{{{len(adjudication['items'])}}}",
    ]
    output = PAPER / "generated_semantic_v04.tex"
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(output)


if __name__ == "__main__":
    main()
