"""Materialize post-audit macro overrides and native figure data from JSON."""
from pathlib import Path
import hashlib,json,re

ROOT=Path(__file__).resolve().parents[2]; PAPER=ROOT/'paper'
ART=ROOT/'artifacts/reviewer_revision_20260919'

def pct(x):return f'{100*x:.1f}'

def main():
    prefix=json.loads((ART/'phi4_mini_corrected_prefix_v1.json').read_text())['summary']
    catalog=json.loads((ART/'phi4_mini_corrected_catalog_v1.json').read_text())['summary']
    legacy=(PAPER/'generated_v09_context.tex').read_text()
    values={'VTwoLargestPrefixGoalDelta':pct(prefix['goal_valid_rate_delta']),
            'VTwoLargestCatalogGoalDelta':pct(catalog['goal_valid_rate_delta'])}
    for label,field in [('Parse','parse'),('Goal','goal_valid'),('Exact','exact_match')]:
        values['VTwoPrefixNormalized'+label]=pct(prefix['normalized_'+field+'_rate'])+r'\%'
        values['VTwoPrefix'+label+'Delta']=pct(prefix[{'Parse':'parse_rate_delta','Goal':'goal_valid_rate_delta','Exact':'exact_match_rate_delta'}[label]])
    lines=['% Generated by generate_reviewer_revision_data.py; legacy inputs retained.']
    for key,value in values.items():lines.append('\\renewcommand{\\'+key+'}{'+value+'}')
    for name,summary,field in [('VTwoSensitivityRows',prefix,'normalized'),('VTwoCatalogProjectionRows',catalog,'projected')]:
        match=re.search(r'\\newcommand\{\\'+name+r'\}\{%(.*?)\n\}',legacy,re.S)
        assert match
        row='Phi-4-mini & '+' & '.join(pct(summary[k]) for k in ['strict_parse_rate',field+'_parse_rate','strict_goal_valid_rate',field+'_goal_valid_rate','strict_exact_match_rate',field+'_exact_match_rate'])+r' \\%'
        body=re.sub(r'Phi-4-mini[^\n]+',lambda m:row,match[1])
        lines.append('\\renewcommand{\\'+name+'}{%'+body+'\n}')
    (PAPER/'generated_reviewer_revision.tex').write_text('\n'.join(lines)+'\n')
    family=json.loads((ART/'family_sensitivity_v1.json').read_text())
    labels={'Qwen/Qwen3-4B':'Qwen3-4B','Qwen/Qwen3-8B':'Qwen3-8B','Qwen/Qwen3-14B':'Qwen3-14B',
            'microsoft/Phi-4-mini-instruct':'Phi-4-mini','mistralai/Mistral-7B-Instruct-v0.3':'Mistral-7B','allenai/OLMo-2-1124-7B-Instruct':'OLMo-2-7B'}
    rows=['model recovered remaining different']
    for model in family['models']:
        c=model['counts']; remaining=c['valid_same_multiset_outside_relaxed']
        rows.append(f"{labels[model['model']]} {c['valid_same_multiset_outside_conservative']-remaining} {remaining} {c['valid_different_multiset']}")
    (PAPER/'data/reviewer_family_decomposition.dat').write_text('\n'.join(rows)+'\n')
    manifest={name:hashlib.sha256((ART/name).read_bytes()).hexdigest() for name in ['corrected_secondary_metric_audit_v1.json','phi4_mini_corrected_prefix_v1.json','phi4_mini_corrected_catalog_v1.json','family_sensitivity_v1.json','external_statistics_v1.json','verifier_stages_costs_v1.json']}
    (PAPER/'data/reviewer_revision_manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')

if __name__=='__main__':main()
