#!/usr/bin/env python3
"""Generate LaTeX macros from the three ICLR revision audits."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


MODEL_NAMES = {
    "Qwen/Qwen3-4B": "Qwen3-4B",
    "microsoft/Phi-4-mini-instruct": "Phi-4-mini",
    "mistralai/Mistral-7B-Instruct-v0.3": "Mistral-7B",
    "allenai/OLMo-2-1124-7B-Instruct": "OLMo-2-7B",
    "Qwen/Qwen3-8B": "Qwen3-8B",
    "Qwen/Qwen3-14B": "Qwen3-14B",
}
MODEL_ORDER = list(MODEL_NAMES)


def pct(value: float) -> str:
    return f"{100 * value:.1f}"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("independent_search", type=Path)
    parser.add_argument("cap_sensitivity", type=Path)
    parser.add_argument("cost_bounded", type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--manifest-output", type=Path)
    args = parser.parse_args()

    independent = json.loads(args.independent_search.read_text(encoding="utf-8"))
    cap = json.loads(args.cap_sensitivity.read_text(encoding="utf-8"))
    cost = json.loads(args.cost_bounded.read_text(encoding="utf-8"))
    independent_summary = independent["summary"]
    cap_summary = cap["summary"]
    cost_by_model = {row["model_id"]: row for row in cost["models"]}
    if set(cost_by_model) != set(MODEL_ORDER):
        raise ValueError("unexpected model set in cost-bounded audit")

    rows = []
    baseline_rates = {}
    zero_cost_rates = {}
    for model_id in MODEL_ORDER:
        model = cost_by_model[model_id]
        threshold_rows = {
            row["normalized_cost_regret_threshold"]: row for row in model["thresholds"]
        }
        rows.append(
            f"{MODEL_NAMES[model_id]} & "
            f"{100 * model['goal_valid_count'] / model['output_count']:.1f} & "
            f"{pct(threshold_rows[0.0]['full_denominator_rate'])} & "
            f"{pct(threshold_rows[0.25]['full_denominator_rate'])} & "
            f"{pct(threshold_rows[0.5]['full_denominator_rate'])} & "
            f"{pct(threshold_rows[1.0]['full_denominator_rate'])} \\\\"
        )
        baseline_rates[model_id] = model["goal_valid_count"] / model["output_count"]
        zero_cost_rates[model_id] = threshold_rows[0.0]["full_denominator_rate"]
    baseline_order = sorted(MODEL_ORDER, key=lambda model_id: baseline_rates[model_id], reverse=True)
    zero_cost_order = sorted(MODEL_ORDER, key=lambda model_id: zero_cost_rates[model_id], reverse=True)
    largest_zero_cost_drop = max(
        baseline_rates[model_id] - zero_cost_rates[model_id] for model_id in MODEL_ORDER
    )

    lines = [
        "% Generated by paper/scripts/generate_revision_audit_data.py; do not edit.",
        f"\\newcommand{{\\IndependentSearchTaskCount}}{{{independent_summary['task_count']}}}",
        f"\\newcommand{{\\IndependentSolvedTaskCount}}{{{independent_summary['tasks_with_independent_solution']}}}",
        f"\\newcommand{{\\IndependentAlternativeTaskCount}}{{{independent_summary['tasks_with_independent_nonreference_solution']}}}",
        f"\\newcommand{{\\IndependentSolutionCount}}{{{independent_summary['independent_solution_count']:,}}}",
        f"\\newcommand{{\\IndependentAlternativeCount}}{{{independent_summary['independent_nonreference_solution_count']:,}}}",
        f"\\newcommand{{\\IndependentBoundedTaskCount}}{{{independent_summary['tasks_hitting_resource_bound']}}}",
        f"\\newcommand{{\\CapSensitiveRepresentativeCount}}{{{cap_summary['capped_representative_count']}}}",
        f"\\newcommand{{\\CapSensitiveTaskCount}}{{{cap_summary['capped_task_count']}}}",
        f"\\newcommand{{\\CurrentRepresentativeCount}}{{{cap_summary['unique_goal_plan_representative_count']:,}}}",
        f"\\newcommand{{\\CurrentMultiplicityTaskCount}}{{{cap_summary['tasks_with_observed_family_multiplicity']}}}",
        f"\\newcommand{{\\CapSensitiveAllValid}}{{{'true' if cap_summary['all_checked_orders_valid_at_every_cap'] else 'false'}}}",
        f"\\newcommand{{\\CapSensitiveMaxOrderCount}}{{{cap_summary['maximum_exact_topological_order_count']:,}}}",
        f"\\newcommand{{\\CostBoundedOrderingPreserved}}{{{'true' if baseline_order == zero_cost_order else 'false'}}}",
        f"\\newcommand{{\\CostBoundedLargestZeroDrop}}{{{100 * largest_zero_cost_drop:.1f}}}",
        "\\newcommand{\\CostBoundedRows}{%",
        *[row + "%" for row in rows],
        "}",
    ]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    if args.manifest_output is not None:
        manifest = {
            "schema_version": "planspace.revision_audits_manifest.v0.1",
            "evidence_status": "post_hoc_revision_audits",
            "audits": [
                {
                    "name": "independent_state_search",
                    "sha256": sha256(args.independent_search),
                    "summary": independent_summary,
                    "boundary": independent["independence_boundary"],
                },
                {
                    "name": "partial_order_cap_sensitivity",
                    "sha256": sha256(args.cap_sensitivity),
                    "summary": cap_summary,
                    "boundary": cap["metric_boundary"],
                },
                {
                    "name": "cost_bounded_goal_validity",
                    "sha256": sha256(args.cost_bounded),
                    "models": [
                        {
                            "model_id": model["model_id"],
                            "output_count": model["output_count"],
                            "goal_valid_count": model["goal_valid_count"],
                            "thresholds": model["thresholds"],
                        }
                        for model in cost["models"]
                    ],
                    "boundary": cost["denominator_policy"],
                },
            ],
        }
        args.manifest_output.parent.mkdir(parents=True, exist_ok=True)
        args.manifest_output.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
