#!/usr/bin/env python3
"""Generate paper macros for the 173-task compatibility-filtered expansion."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MODEL_ID = "Qwen/Qwen3-8B"
SPLIT_LABELS = {
    "iid_core": "Core",
    "ood_commutation": "Commutation",
    "ood_goal_choice": "Goal choice",
    "ood_long_horizon": "Long horizon",
    "ood_operator_composition": "Operator composition",
}


def pct(value: float) -> str:
    return f"{100 * value:.1f}"


def summarize_new_tasks(enriched: dict, original_queue: dict) -> tuple[int, float, float, float, float, int, float, float, float]:
    """Compute disjoint new-task rates from the frozen expansion outputs."""
    original_sources = {row["source_path"] for row in original_queue["records"]}
    by_source = {row["source_path"]: row for row in enriched["tasks"]}
    overlap = set(by_source) & original_sources
    new_tasks = [row for source, row in by_source.items() if source not in original_sources]
    original_tasks = [row for source, row in by_source.items() if source in original_sources]
    if len(new_tasks) + len(overlap) != len(by_source):
        raise ValueError("expanded task partition is inconsistent")
    samples = [sample for task in new_tasks for sample in task["samples"]]
    if len(samples) != 5 * len(new_tasks):
        raise ValueError("new-task expansion must contain five samples per task")
    goal = sum(bool((sample.get("execution") or {}).get("valid")) for sample in samples) / len(samples)
    partial = sum(bool(sample.get("partial_order_match")) for sample in samples) / len(samples)
    exact = sum(bool(sample.get("exact_match")) for sample in samples) / len(samples)
    original_samples = [sample for task in original_tasks for sample in task["samples"]]
    if len(original_samples) != 5 * len(overlap):
        raise ValueError("overlap must contain five samples for each original task")
    original_goal = sum(
        bool((sample.get("execution") or {}).get("valid")) for sample in original_samples
    ) / len(original_samples)
    original_partial = sum(
        bool(sample.get("partial_order_match")) for sample in original_samples
    ) / len(original_samples)
    original_exact = sum(bool(sample.get("exact_match")) for sample in original_samples) / len(original_samples)
    return (
        len(new_tasks), goal, partial, exact, goal - exact, len(overlap),
        original_goal, original_partial, original_exact,
    )


def render(comparison: dict, analysis: dict, queue: dict, *, enriched: dict | None = None, original_queue: dict | None = None) -> str:
    aggregate = comparison.get("aggregate", {})
    if MODEL_ID not in aggregate:
        raise ValueError("expanded comparison must contain Qwen3-8B")
    selected_count = int(queue.get("selected_count", 0))
    excluded_count = int(queue.get("excluded_count", 0)) + int(
        queue.get("context_excluded_count", 0)
    )
    if selected_count <= 0:
        raise ValueError("expanded queue must declare a positive selected_count")
    splits = analysis.get("strata", {}).get("structural_split", {})
    if set(splits) != set(SPLIT_LABELS):
        raise ValueError("expanded analysis has an unexpected structural split set")
    if sum(row["task_count"] for row in splits.values()) != selected_count:
        raise ValueError("expanded split task counts do not sum to selected_count")
    overall = aggregate[MODEL_ID]
    new_summary = summarize_new_tasks(enriched, original_queue) if enriched and original_queue else None
    lines = [
        "% Generated by paper/scripts/generate_expanded_coverage_data.py; do not edit.",
        rf"\newcommand{{\ExpandedSupportedTaskCount}}{{{selected_count}}}",
        rf"\newcommand{{\ExpandedExcludedTaskCount}}{{{excluded_count}}}",
        rf"\newcommand{{\ExpandedGoalValid}}{{{pct(overall['goal_valid'])}}}",
        rf"\newcommand{{\ExpandedPartialOrder}}{{{pct(overall['partial_order'])}}}",
        rf"\newcommand{{\ExpandedExact}}{{{pct(overall['exact'])}}}",
        r"\newcommand{\ExpandedCoverageTable}{%",
        r"\begin{table}[ht]",
        r"\centering",
        rf"\caption{{Qwen3-8B on the compatibility-filtered and shared-context-filtered {selected_count}-task set under the same v0.4 action semantics and uniform compact prompt. Rates are percentages over five samples per task. The rows describe the structural composition of this supported set.}}",
        r"\label{tab:expanded-coverage}",
        r"\small",
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Split & Tasks & Goal & Partial & Exact \\",
        r"\midrule",
    ]
    if new_summary:
        (
            new_count, new_goal, new_partial, new_exact, new_gap, overlap_count,
            original_goal, original_partial, original_exact,
        ) = new_summary
        lines[6:6] = [
            rf"\newcommand{{\ExpandedOverlapTaskCount}}{{{overlap_count}}}",
            rf"\newcommand{{\ExpandedNewTaskCount}}{{{new_count}}}",
            rf"\newcommand{{\ExpandedNewGoalValid}}{{{pct(new_goal)}}}",
            rf"\newcommand{{\ExpandedNewPartialOrder}}{{{pct(new_partial)}}}",
            rf"\newcommand{{\ExpandedNewExact}}{{{pct(new_exact)}}}",
            rf"\newcommand{{\ExpandedNewGoalExactGap}}{{{pct(new_gap)}}}",
            rf"\newcommand{{\ExpandedOriginalGoalValid}}{{{pct(original_goal)}}}",
            rf"\newcommand{{\ExpandedOriginalPartialOrder}}{{{pct(original_partial)}}}",
            rf"\newcommand{{\ExpandedOriginalExact}}{{{pct(original_exact)}}}",
        ]
    for split_name, label in SPLIT_LABELS.items():
        row = splits[split_name]
        lines.append(
            f"{label} & {row['task_count']} & {pct(row['goal_valid_rate'])} & "
            f"{pct(row['partial_order_match_rate'])} & {pct(row['exact_match_rate'])} \\\\")
    if new_summary:
        new_count, new_goal, new_partial, new_exact, *_ = new_summary
        lines.append(
            "New %d only & %d & %s & %s & %s \\\\"
            % (new_count, new_count, pct(new_goal), pct(new_partial), pct(new_exact))
        )
    lines.extend(
        [
            r"\midrule",
            f"Overall & {selected_count} & {pct(overall['goal_valid'])} & {pct(overall['partial_order'])} & {pct(overall['exact'])} \\\\",
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}%",
            r"}",
        ]
    )
    figure_splits = (
        "ood_operator_composition",
        "ood_long_horizon",
        "ood_goal_choice",
        "ood_commutation",
        "iid_core",
    )
    for metric, macro in (
        ("exact_match_rate", "Exact"),
        ("partial_order_match_rate", "Partial"),
        ("goal_valid_rate", "Goal"),
    ):
        coordinates = " ".join(
            f"({pct(splits[split][metric])},{index})"
            for index, split in enumerate(figure_splits, start=1)
        )
        lines.append(f"\\newcommand{{\\ExpandedFigure{macro}Coordinates}}{{{coordinates}}}")
    lines.append(r"\newcommand{\ExpandedFigureGapSegments}{%")
    for index, split in enumerate(figure_splits, start=1):
        row = splits[split]
        lines.append(
            r"\addplot[psGrid,line width=2.2pt] coordinates {(%s,%d) (%s,%d)};%%"
            % (pct(row["exact_match_rate"]), index, pct(row["goal_valid_rate"]), index)
        )
    lines.append("}")
    lines.append(r"\newcommand{\ExpandedFigureGapAnnotations}{%")
    for index, split in enumerate(figure_splits, start=1):
        row = splits[split]
        gap = 100 * (row["goal_valid_rate"] - row["exact_match_rate"])
        if gap > 10:
            lines.append(
                r"\node[font=\sffamily\scriptsize,text=psAccent,anchor=west] at (axis cs:%s,%d) {%.1f pp};%%"
                % (pct(row["goal_valid_rate"] + 0.012), index, gap)
            )
    lines.append("}")
    if new_summary:
        lines.extend(
            (
                r"\newcommand{\ExpandedFigureReplicationExactCoordinates}{(Original,%s) (New,%s) (All,%s)}"
                % (pct(original_exact), pct(new_exact), pct(overall["exact"])),
                r"\newcommand{\ExpandedFigureReplicationPartialCoordinates}{(Original,%s) (New,%s) (All,%s)}"
                % (pct(original_partial), pct(new_partial), pct(overall["partial_order"])),
                r"\newcommand{\ExpandedFigureReplicationGoalCoordinates}{(Original,%s) (New,%s) (All,%s)}"
                % (pct(original_goal), pct(new_goal), pct(overall["goal_valid"])),
            )
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--result-dir", type=Path, default=ROOT / "artifacts")
    parser.add_argument("--output", type=Path, default=ROOT / "paper" / "generated_expanded_v07.tex")
    parser.add_argument("--suffix", default="v0_7_expanded")
    parser.add_argument("--task-count", type=int, default=173)
    parser.add_argument(
        "--queue",
        type=Path,
        default=ROOT / "artifacts" / "action_semantics_supported_queue_173_v0_1.json",
    )
    args = parser.parse_args()
    suffix = args.suffix
    comparison = json.loads((args.result_dir / f"multi_model_comparison_{suffix}.json").read_text(encoding="utf-8"))
    analysis = json.loads(
        (
            args.result_dir
            / f"qwen3_8b_queue_{args.task_count}_analysis_{suffix}.json"
        ).read_text(encoding="utf-8")
    )
    queue = json.loads(args.queue.read_text(encoding="utf-8"))
    enriched = json.loads(
        (
            args.result_dir
            / f"qwen3_8b_queue_{args.task_count}_enriched_{suffix}.json"
        ).read_text(encoding="utf-8")
    )
    original_queue = json.loads((ROOT / "artifacts" / "action_semantics_review_queue_100_v0_4.json").read_text(encoding="utf-8"))
    args.output.write_text(
        render(comparison, analysis, queue, enriched=enriched, original_queue=original_queue),
        encoding="utf-8",
    )
    print(args.output)


if __name__ == "__main__":
    main()
