#!/usr/bin/env python3
"""Generate paper macros for the blinded output-level AI audit."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ARTIFACT = ROOT / "artifacts" / "output_validity_ai_adjudicated_v0_1.json"
OUTPUT = ROOT / "paper" / "generated_output_validity.tex"


def pct(value: float) -> str:
    return f"{100 * value:.1f}"


def main() -> None:
    report = json.loads(ARTIFACT.read_text(encoding="utf-8"))
    if report["evidence_status"] != "internal_ai_output_validity_audit_not_human_validation":
        raise ValueError("unexpected output-validity evidence boundary")
    if report["case_count"] != 120:
        raise ValueError("output-validity audit must contain 120 cases")
    agreement = report["agreement"]
    metrics = report["metric_validity_against_ai_consensus"]
    rows = []
    labels = {
        "exact_match": "Exact match",
        "partial_order_match": "Partial-order match",
        "goal_valid": "Goal-valid replay",
    }
    for key in ("exact_match", "partial_order_match", "goal_valid"):
        row = metrics[key]
        rows.append(
            f"{labels[key]} & {pct(row['accuracy'])} & {pct(row['precision'])} & "
            f"{pct(row['recall'])} & {pct(row['f1'])} \\\\"
        )
    rows.append(
        "Ordered-action similarity & -- & -- & -- & "
        f"AUROC {metrics['ordered_action_similarity']['auroc']:.3f} \\\\"
    )
    lines = [
        "% Generated by paper/scripts/generate_output_validity_data.py; do not edit.",
        rf"\newcommand{{\OutputAuditCaseCount}}{{{report['case_count']}}}",
        rf"\newcommand{{\OutputAuditFinalLabeledCount}}{{{report['consensus_reasonable_case_count']}}}",
        rf"\newcommand{{\OutputAuditAdjudicationCount}}{{{report['adjudication_case_count']}}}",
        rf"\newcommand{{\OutputAuditBehaviorAgreement}}{{{pct(agreement['reasonable_high_level_behavior']['agreement_rate'])}}}",
        rf"\newcommand{{\OutputAuditBehaviorKappa}}{{{agreement['reasonable_high_level_behavior']['cohen_kappa']:.3f}}}",
        rf"\newcommand{{\OutputAuditValidityAgreement}}{{{pct(agreement['valid_at_declared_abstraction']['agreement_rate'])}}}",
        rf"\newcommand{{\OutputAuditValidityKappa}}{{{agreement['valid_at_declared_abstraction']['cohen_kappa']:.3f}}}",
        "\\newcommand{\\OutputValidityRows}{%",
        *(row + "%" for row in rows),
        "}",
    ]
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(OUTPUT)


if __name__ == "__main__":
    main()
