#!/usr/bin/env python3
"""Generate an appendix table for the v0.6-to-v0.8 overlap diagnostic."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MODEL_LABELS = {
    "Qwen/Qwen3-4B": "Qwen3-4B",
    "microsoft/Phi-4-mini-instruct": "Phi-4-mini",
    "mistralai/Mistral-7B-Instruct-v0.3": "Mistral-7B",
    "allenai/OLMo-2-1124-7B-Instruct": "OLMo-2-7B",
    "Qwen/Qwen3-8B": "Qwen3-8B",
    "Qwen/Qwen3-14B": "Qwen3-14B",
}


def pct(value: float) -> str:
    return f"{100 * value:.1f}"


def signed_pp(value: float) -> str:
    return f"{100 * value:+.1f}"


def render(report: dict) -> str:
    if report.get("evidence_status") != "posthoc_cross_run_diagnostic":
        raise ValueError("cross-run report must be labeled posthoc_cross_run_diagnostic")
    overlap_task_count = int(report.get("overlap_task_count", 0))
    if overlap_task_count <= 0:
        raise ValueError("cross-run diagnostic must cover a non-empty task overlap")
    overlap_sample_count = 5 * overlap_task_count
    records = report.get("models", [])
    by_model = {row.get("model_id"): row for row in records}
    if set(by_model) != set(MODEL_LABELS):
        raise ValueError("cross-run diagnostic must contain the frozen six-model set")
    rows = []
    max_abs_drift = 0.0
    raw_match_rates = []
    for model_id, label in MODEL_LABELS.items():
        row = by_model[model_id]
        if (
            row.get("overlap_task_count") != overlap_task_count
            or row.get("overlap_sample_count") != overlap_sample_count
        ):
            raise ValueError(f"incomplete overlap for {model_id}")
        if row.get("prompt_hash_match_task_count") != overlap_task_count:
            raise ValueError(f"prompt hash drift for {model_id}")
        if row.get("serialized_chat_hash_match_task_count") != overlap_task_count:
            raise ValueError(f"serialized-chat drift for {model_id}")
        metrics = row.get("metrics", {})
        if set(metrics) != {"parse", "executable", "goal_valid", "exact"}:
            raise ValueError(f"incomplete metric drift for {model_id}")
        max_abs_drift = max(
            max_abs_drift,
            *(abs(item["new_minus_old"]) for item in metrics.values()),
        )
        raw_match = row["raw_output_match_rate"]
        raw_match_rates.append(raw_match)
        rows.append(
            f"{label} & {overlap_task_count}/{overlap_task_count} & "
            f"{row['seed_match_sample_count']}/{overlap_sample_count} & "
            f"{pct(raw_match)} & {signed_pp(metrics['goal_valid']['new_minus_old'])} & "
            f"{signed_pp(metrics['exact']['new_minus_old'])} \\\\"
        )
    lines = [
        "% Generated by paper/scripts/generate_cross_run_reproducibility_data.py; do not edit.",
        rf"\newcommand{{\CrossRunOverlapTaskCount}}{{{overlap_task_count}}}",
        rf"\newcommand{{\CrossRunOverlapSampleCount}}{{{overlap_sample_count}}}",
        rf"\newcommand{{\CrossRunMinRawMatch}}{{{pct(min(raw_match_rates))}}}",
        rf"\newcommand{{\CrossRunMaxRawMatch}}{{{pct(max(raw_match_rates))}}}",
        rf"\newcommand{{\CrossRunMaxAbsMetricDrift}}{{{pct(max_abs_drift)}}}",
        r"\newcommand{\CrossRunReproducibilityTable}{%",
        r"\begin{table}[ht]",
        r"\centering",
        rf"\caption{{Post-hoc overlap diagnostic between the archived v0.6 run and the shared-context-filtered matrix. Prompts and serialized chats match on all {overlap_task_count} overlapping tasks. Seed agreement is reported per checkpoint, so this is not a same-seed confirmatory experiment. Metric columns are new minus archived percentage points.}}",
        r"\label{tab:cross-run-reproducibility}",
        r"\small",
        r"\begin{tabular}{lrrrrr}",
        r"\toprule",
        r"Model & Prompt & Seed & Raw match (\%) & $\Delta$Goal & $\Delta$Exact \\",
        r"\midrule",
        *rows,
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}%",
        r"}",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        type=Path,
        default=ROOT / "artifacts" / "cross_run_reproducibility_v0_6_to_v0_8.json",
    )
    parser.add_argument(
        "--output", type=Path, default=ROOT / "paper" / "generated_cross_run_v08.tex"
    )
    args = parser.parse_args()
    report = json.loads(args.input.read_text(encoding="utf-8"))
    args.output.write_text(render(report), encoding="utf-8")
    print(args.output)


if __name__ == "__main__":
    main()
