#!/usr/bin/env python3
"""Generate appendix macros for the model-output-independent context audit."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


def escape(value: str) -> str:
    return value.replace("_", r"\_")


def render(audit: dict) -> str:
    rows = audit.get("records", [])
    excluded = [row for row in rows if not row["fits_requested_budget"]]
    if len(rows) != audit["retained_count"] + audit["excluded_count"]:
        raise ValueError("context audit counts are inconsistent")
    if len(excluded) != audit["excluded_count"]:
        raise ValueError("context audit exclusion count is inconsistent")
    table_rows = []
    for row in excluded:
        activity = row["source_path"].split("/", 1)[0]
        total = row["input_tokens"] + row["requested_max_new_tokens"]
        table_rows.append(
            f"{escape(activity)} & {row['input_tokens']:,} & "
            f"{row['requested_max_new_tokens']:,} & {total:,} \\\\"
        )
    lines = [
        "% Generated by paper/scripts/generate_context_compatibility_data.py; do not edit.",
        rf"\newcommand{{\ContextAuditCandidateCount}}{{{len(rows)}}}",
        rf"\newcommand{{\ContextAuditRetainedCount}}{{{audit['retained_count']}}}",
        rf"\newcommand{{\ContextAuditExcludedCount}}{{{audit['excluded_count']}}}",
        rf"\newcommand{{\ContextAuditLimit}}{{{audit['context_limit']:,}}}",
        rf"\newcommand{{\ContextAuditOutputBudget}}{{{audit['requested_max_new_tokens']:,}}}",
        r"\newcommand{\ContextCompatibilityTable}{%",
        r"\begin{table}[ht]",
        r"\centering",
        r"\caption{Model-output-independent shared-context audit. A task is excluded only when its frozen serialized chat plus the common output budget exceeds the smallest checkpoint context window.}",
        r"\label{tab:context-compatibility}",
        r"\small",
        r"\begin{tabular}{lrrr}",
        r"\toprule",
        r"Activity & Input tokens & Output budget & Required total \\",
        r"\midrule",
        *table_rows,
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}%",
        r"}",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        type=Path,
        default=ROOT / "artifacts" / "prompt_context_compatibility_173_v0_1.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "paper" / "generated_context_compatibility.tex",
    )
    args = parser.parse_args()
    args.output.write_text(
        render(json.loads(args.input.read_text(encoding="utf-8"))),
        encoding="utf-8",
    )
    print(args.output)


if __name__ == "__main__":
    main()
