#!/usr/bin/env python3
"""Generate conservative coverage-funnel macros from v0.5 audit artifacts."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ARTIFACTS = ROOT / "artifacts"
PAPER = ROOT / "paper"


def load(name: str) -> dict:
    return json.loads((ARTIFACTS / name).read_text(encoding="utf-8"))


def main() -> None:
    source = load("bddl_source_audit_v05.json")
    screen = load("structural_screen_202_v05.json")
    translation = load("compatibility_translation_audit_202_v05.json")
    domain = load("generic_domain_audit_175_v05.json")
    if source["parsed_count"] != source["problem_file_count"]:
        raise ValueError("source parsing is incomplete")
    if screen["source_problem_file_count"] != source["problem_file_count"]:
        raise ValueError("screen/source cardinality mismatch")
    if sum(translation["translation_status_counts"].values()) != screen["selected_count"]:
        raise ValueError("translation funnel does not cover structural candidates")
    summary = domain["summary"]
    if summary["queue_task_count"] != translation["translation_status_counts"]["pass"]:
        raise ValueError("domain audit does not cover translation passes")
    if not summary["all_stored_plans_validate"]:
        raise ValueError("candidate stored plans did not validate")
    lines = [
        "% Generated by paper/scripts/generate_coverage_v05_data.py; do not edit.",
        rf"\newcommand{{\CoverageVFiveSourceCount}}{{{source['problem_file_count']}}}",
        rf"\newcommand{{\CoverageVFiveStructuralCount}}{{{screen['eligible_count']}}}",
        rf"\newcommand{{\CoverageVFiveTranslationCount}}{{{translation['translation_status_counts']['pass']}}}",
        rf"\newcommand{{\CoverageVFiveCandidateDomainCount}}{{{summary['fully_candidate_supported_task_count']}}}",
        rf"\newcommand{{\CoverageVFiveTopologyChecked}}{{{summary['topological_orders_checked']:,}}}",
    ]
    (PAPER / "generated_coverage_v05.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
