import importlib.util
from pathlib import Path

import pytest


SCRIPT = Path(__file__).parents[1] / "scripts" / "verify_v04_claims.py"
SPEC = importlib.util.spec_from_file_location("verify_v04_claims", SCRIPT)
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)


def write_fixture(tmp_path: Path, text: str) -> tuple[Path, Path]:
    manuscript = tmp_path / "main.tex"
    generated = tmp_path / "generated_v04.tex"
    manuscript.write_text(text, encoding="utf-8")
    generated.write_text(
        "% Generated by paper/scripts/generate_v02_data.py from v0_4; do not edit.\n"
        r"\newcommand{\VTwoBehaviorGapModelCount}{5}" + "\n",
        encoding="utf-8",
    )
    return manuscript, generated


def test_rejects_hand_written_result_percentage(tmp_path: Path):
    manuscript, generated = write_fixture(
        tmp_path,
        r"\input{generated_v04.tex}\begin{abstract}\VTwoBehaviorGapModelCount{} of"
        r"\end{abstract}\section{Results}Phi improves by 20.6\%.\section{Limitations}",
    )
    with pytest.raises(AssertionError, match="hand-written percentage"):
        MODULE.verify(manuscript, generated)


def test_accepts_generated_result_claims(tmp_path: Path):
    manuscript, generated = write_fixture(
        tmp_path,
        r"\input{generated_v04.tex}\begin{abstract}\VTwoBehaviorGapModelCount{} of"
        r"\end{abstract}\section{Results}See Table~\ref{tab:x}.\section{Limitations}",
    )
    MODULE.verify(manuscript, generated)
